### ISSUE TITLE
Will calling psel and get_btg with the same dataframe and pref do twice the work?

### ISSUE THREAD

**Issue by GitChub** [patrickroocks/rpref#1]
First off, nice work on this package!

I have a use case in which I want to get the BTG, but I'm also interested in the show_level option of psel.  If I call both psel and get_btg with the same dataframe and pref, will the work of the query actually be done twice?  Or does the package cache results internally to avoid double work?  Any suggestions for minimizing the work done by the package in the situation I've outlined?

Thanks in advance!

**Comment by patrickroocks** [comment]
Thanks for your feedback!

The work is done twice, there is no internal caching at the moment. The preference selection (`psel`) is encoded quite efficiently to work also on large data sets, even when `top=nrow(df)` is set (to get the level value of all tuples). 

In contrast to that, the `get_btg` function follows the naive approach of calculating the transitive reduction (3 nested for-loops, see hasse.cpp, resulting in an O(n^3) algorithm) which is definitively not the most efficient way to do that. The BTG functionality is mainly intended for visualizing graphs, and probably ~100 nodes is the maximum what makes sense to visualize in one diagram. As for ~100 nodes the current approach works "instantaneously" (run time less than 1ms) I did not care about performance issues concerning the transitive reduction.

Do you intend to work with the BTG on very large data sets?

**Comment by GitChub** [comment]
Thanks for the quick and thorough reply Patrick.

For now, my BTGs will be limited to, at most, about 200 vertices, with 20 to 80 vertices being most common (fortunately).  However, there will be numerous BTGs generated from potentially many concurrent users, so I'm trying to be careful about performance.

Even if the data sets get larger than that, it probably makes sense to limit the number of vertices included in the BTG for larger data sets by using the `top_level` or `top` options of `psel`.  So the `get_transitive_reduction` algorithm being O(n^3) shouldn't become a practical concern.

**Comment by GitChub** [comment]
I took a cursory look at the code for `get_transitive_reduction`.   If I understand what's happening in the nested loops correctly (a big if at this point), it appears to me that tuples are being compared to themselves, which I suppose could be skipped. 

So perhaps this line of code
`if (p->cmp(i, j)) {`

... could be this?
`if (i != j && p->cmp(i, j)) {`

If that's the case, then this line of code
`if (p->cmp(i, k) && p->cmp(k, j)) {`

... can probably also be this:
`if (k != i && k != j && p->cmp(i, k) && p->cmp(k, j)) {`

It's a pretty trivial observation, but I thought I'd mention it anyway.

Thanks again for the fantastic work on this package!

**Comment by patrickroocks** [comment]
You are totally right, this could be done. 

But I am not sure if this an optimization. This adds O(n^2) integer comparisons and avoids O(n) float comparisons (to show that `p->cmp(i,j)` is false, we need k float comparisons for a k-dimensional Pareto preference and usually k is very small, k=2 or k=3 typically...) If you evaluate this optimization, let me know if this is a performance gain for your examples :)

**Comment by GitChub** [comment]
Yeah, I was thinking about it later while driving and it crossed my mind that those `cmp()` calls were probably pretty low cost and could easily be outweighed by the O(n^2) integer comparisons.

If I do happen to stumble on any verified optimizations, I'll be sure to share them.  :)

**Comment by patrickroocks** [comment]
Probably it would bring more benefits to rewrite the transitive reduction ( O(n^2.3729) is possible as noted in https://en.wikipedia.org/wiki/Transitive_reduction#Computational_complexity ), but I am not an expert in this. Perhaps something for one of the next versions :)
